apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-component
  description: A simple Backstage component
  tags:
    - example
  annotations:
    github.com/project-slug: my-org/my-backstage-component
spec:
  type: service
  owner: my-team
  lifecycle: experimental
